LIB = ./lib
OBJ = ./obj
SRC = ./src/libnfe
INCLUDE = ./include/libnfe

CFLAGS = -Wall -Werror -g -std=c89

all: libtooldoce

libtooldoce: $(OBJ)/*.o
	ar -rcs $(LIB)/libtooldoce.a $(OBJ)/*.o

$(OBJ)/%.o: $(SRC)/%.c $(SRC)/%.h $(INCLUDE)/%.h
	gcc $(CFLAGS) -c $< -I $(INCLUDE) -I $(SRC) -o $@

clean:
	rm $(OBJ)/*.o
