#!/usr/bin/env python3
"""Gera o texto das issues de implementação de cada estrutura da NF-e.

Usa o mesmo modelo de tools/gerar_diagramas.py (lido do XSD oficial) e
escreve um arquivo Markdown por estrutura em um diretório de saída, com:
título, diagrama, tabela de campos (obrigatoriedade, ocorrências, tipo,
tamanho, valores e padrão), funções a implementar (criação/liberação,
setters com as validações do leiaute, inclusão de filhos, escrita do XML)
e critérios de aceite.

Uso (na raiz do projeto):
    python3 tools/gerar_issues.py SAIDA [--repo dono/repositorio]

Cada arquivo começa com uma linha "título: ..." seguida do corpo da issue.
Estruturas de um mesmo tipo nomeado usado em vários lugares (ex.: TDif)
geram uma issue só. Também é gerado SAIDA/indice.tsv com: número do
arquivo, chave, chave do pai, "feito" (já marcado no TODO.md) e título.
"""
import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import gerar_diagramas as gd  # noqa: E402

RODAPE = "\n---\n_Generated by [Claude Code](https://claude.ai/code)_\n"


def chave_grupo(e, compartilhados):
    """Estruturas do mesmo tipo nomeado usado em mais de um lugar (ex.: TDif)
    têm uma implementação só e, portanto, uma issue só."""
    return e.tipo if e.tipo in compartilhados else e.caminho


def tipos_compartilhados(estruturas):
    contagem = {}
    for e in estruturas:
        if e.tipo:
            contagem[e.tipo] = contagem.get(e.tipo, 0) + 1
    return {t for t, n in contagem.items() if n > 1}


def nomes_unicos(estruturas):
    """Nome curto de cada estrutura para as funções (nfe_<nome>_...).

    Usa o nome do elemento; se ele se repetir em outro caminho, junta o
    nome do pai (ex.: impostoDevol/IPI -> impostodevol_ipi)."""
    compartilhados = tipos_compartilhados(estruturas)
    contagem = {}
    for e in estruturas:
        if e.tipo not in compartilhados:
            contagem[e.nome] = contagem.get(e.nome, 0) + 1
    nomes = {}
    for e in estruturas:
        if e.tipo in compartilhados:
            nome = e.tipo[1:] if e.tipo.startswith("T") else e.tipo
        elif contagem[e.nome] == 1:
            nome = e.nome
        else:
            nome = "_".join(e.caminho.split("/")[-2:])
        nomes[e.caminho] = nome.lower()
    return nomes


def descreve_validacao(f, tipo):
    """Texto da validação de um campo simples, a partir das facetas."""
    v = []
    if "enumeration" in f:
        v.append("valores: " + ", ".join(f"`{x}`" for x in f["enumeration"]))
    if "length" in f:
        v.append(f"tamanho exato {f['length']}")
    elif "minLength" in f or "maxLength" in f:
        v.append(f"tamanho {f.get('minLength', '0')} a "
                 f"{f.get('maxLength', '?')} caracteres")
    if "pattern" in f:
        v.append(f"padrão `{f['pattern']}`")
    if not v and tipo:
        v.append(f"tipo `{tipo}`")
    return "; ".join(v)


def tipo_c(f, tipo):
    """Tipo C sugerido para o setter de um campo simples."""
    t = (tipo or "").lower()
    if t.startswith("tdec"):
        return "const char *"  # decimal com casas fixas: texto validado
    return "const char *"


def itens_com_contexto(grupo, escolha=None):
    """(item, rótulo da escolha) de cada elemento, atravessando grupos."""
    for item in grupo.itens:
        if isinstance(item, gd.Grupo):
            rotulo = escolha
            if item.tipo == "choice":
                rotulo = "escolha"
            yield from itens_com_contexto(item, rotulo)
        else:
            yield item, escolha


def escape_tabela(t):
    return t.replace("|", "\\|")


def url_svg(repo, caminho):
    return f"https://github.com/{repo}/blob/master/docs/diagramas/{caminho}.svg"


def corpo_issue(locais, nomes, repo, pais):
    """Corpo da issue de uma implementação; locais = estruturas (mesmo tipo)
    em que ela aparece."""
    e = locais[0]
    nome = nomes[e.caminho]
    linhas = []
    if len(locais) == 1:
        linhas.append(f"## Estrutura `{e.caminho.replace('/', ' › ')}`")
    else:
        linhas.append(f"## Tipo `{e.tipo}` (`{e.nome}`)")
    linhas.append("")
    if e.doc:
        linhas.append(f"{e.doc}")
        linhas.append("")
    if len(locais) > 1:
        linhas.append(f"Uma única implementação, usada em {len(locais)} "
                      "lugares do leiaute:")
        linhas.append("")
    for loc in locais:
        oc = gd.ocorrencia(loc.minimo, loc.maximo) or "1"
        pai = pais.get(loc.caminho)
        txt = f"- `{loc.caminho.replace('/', ' › ')}` — ocorrência `{oc}`"
        if loc.minimo == "0":
            txt += " (opcional)"
        if pai:
            txt += f", dentro de `{pai.nome}`"
        txt += f" — [diagrama]({url_svg(repo, loc.caminho)})"
        linhas.append(txt)
    linhas.append("")
    relacionadas = {
        "NFe": "#69 (gerar o XML completo da NF-e) e #56 (assinatura)",
        "NFe/infNFe": "#69 (gerar o XML completo da NF-e) e #54 "
                      "(chave de acesso, usada no atributo `Id`)",
    }
    if e.caminho in relacionadas:
        linhas.append(f"Relacionadas: {relacionadas[e.caminho]}.")
        linhas.append("")
    linhas.append(f"![Diagrama de {e.nome}]({url_svg(repo, e.caminho)}"
                  "?raw=true)")
    linhas.append("")

    # campos
    linhas.append("## Campos")
    linhas.append("")
    linhas.append("| Campo | Obrig. | Ocorr. | Tipo | Validação | Descrição |")
    linhas.append("|---|---|---|---|---|---|")
    for at in e.atributos:
        linhas.append(
            f"| `{at.nome}` | {'sim' if at.minimo == '1' else 'não'} | | "
            f"{escape_tabela(at.tipo)} | "
            f"{escape_tabela(descreve_validacao(at.facetas, at.tipo))} | "
            f"{escape_tabela(at.doc)} |")
    escolhas = False
    for item, ctx in itens_com_contexto(e.conteudo):
        escolhas = escolhas or ctx == "escolha"
        obrig = "não" if item.minimo == "0" else (
            "escolha" if ctx == "escolha" else "sim")
        ocorr = gd.ocorrencia(item.minimo, item.maximo) or "1"
        if item.estrutura:
            tipo = "estrutura"
            val = f"ver issue/diagrama de `{item.nome}`"
        elif ":" in item.nome:
            tipo = item.tipo
            val = "gerado pela assinatura digital (#56), não por setter"
        else:
            tipo = item.tipo
            val = descreve_validacao(item.facetas, item.tipo)
        linhas.append(f"| `{item.nome}` | {obrig} | {ocorr} | "
                      f"{escape_tabela(tipo)} | {escape_tabela(val)} | "
                      f"{escape_tabela(item.doc)} |")
    linhas.append("")
    if escolhas:
        linhas.append("> Campos marcados como **escolha** pertencem a um "
                      "`xs:choice`: apenas um ramo pode ser informado "
                      "(ver o diagrama).")
        linhas.append("")

    # funções
    linhas.append("## Funções a implementar")
    linhas.append("")
    linhas.append("Seguindo `docs/CONVENCOES.md` (tipo opaco, retorno `int` "
                  "com códigos de `erros.h`, sem impressão):")
    linhas.append("")
    linhas.append(f"- [ ] `nfe_{nome} *nfe_{nome}_new(void)` — cria com "
                  "valores padrão; `NULL` se faltar memória")
    linhas.append(f"- [ ] `void nfe_{nome}_free(nfe_{nome} *obj)` — libera "
                  "o objeto e os filhos que ele possui; aceita `NULL`")
    for at in e.atributos:
        linhas.append(f"- [ ] `int nfe_{nome}_set_{at.nome[1:].lower()}"
                      f"(nfe_{nome} *obj, const char *valor)` — atributo")
    for item, ctx in itens_com_contexto(e.conteudo):
        campo = item.nome.lower()
        if ":" in item.nome:
            continue  # ds:Signature: produzido pela assinatura (#56)
        if item.estrutura:
            filho = nomes.get(item.caminho, campo)
            if item.maximo not in ("1", "0"):
                lim = "sem limite" if item.maximo == "unbounded" \
                    else f"até {item.maximo}"
                linhas.append(
                    f"- [ ] `int nfe_{nome}_add_{campo}(nfe_{nome} *obj, "
                    f"nfe_{filho} *{campo})` — inclui um `{item.nome}` "
                    f"({lim}); o objeto passa a ser dono do filho")
            else:
                linhas.append(
                    f"- [ ] `int nfe_{nome}_set_{campo}(nfe_{nome} *obj, "
                    f"nfe_{filho} *{campo})` — define o `{item.nome}`; o "
                    f"objeto passa a ser dono do filho")
        else:
            if item.maximo not in ("1", "0"):
                linhas.append(
                    f"- [ ] `int nfe_{nome}_add_{campo}(nfe_{nome} *obj, "
                    f"{tipo_c(item.facetas, item.tipo)}valor)` — repetível "
                    f"({gd.ocorrencia(item.minimo, item.maximo)})")
            else:
                linhas.append(
                    f"- [ ] `int nfe_{nome}_set_{campo}(nfe_{nome} *obj, "
                    f"{tipo_c(item.facetas, item.tipo)}valor)`")
    linhas.append(f"- [ ] `int nfe_{nome}_write_xml(xmlTextWriterPtr writer, "
                  f"const nfe_{nome} *obj)` — escreve `<{e.nome}>` na ordem "
                  "do leiaute; recusa (`E_VALOR`) se faltar campo "
                  "obrigatório ou se mais de um ramo de uma escolha estiver "
                  "preenchido")
    linhas.append("")
    linhas.append("Cada setter valida o valor conforme a coluna *Validação* "
                  "da tabela; "
                  "tamanhos em caracteres UTF-8. Valores decimais (`TDec_*`) são recebidos como "
                  "texto e validados contra o padrão; CNPJ/CPF usam "
                  "`nfe_cnpj_validar`/`nfe_cpf_validar`.")
    linhas.append("")

    # aceite
    linhas.append("## Critérios de aceite")
    linhas.append("")
    linhas.append("- [ ] Header em `include/libnfe/` e implementação em "
                  "`src/libnfe/`, formatados (`make formatar`)")
    linhas.append("- [ ] Testes em `tests/` cobrindo cada setter (valores "
                  "válidos e inválidos) e a escrita do XML")
    linhas.append("- [ ] XML gerado validado contra o XSD oficial nos testes")
    linhas.append("- [ ] Item marcado no `TODO.md`")
    linhas.append("")
    linhas.append("_Gerado a partir de `leiauteNFe_v4.00.xsd` por "
                  "`tools/gerar_issues.py`._")
    return "\n".join(linhas) + "\n" + RODAPE


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("saida")
    ap.add_argument("--repo", default="icaroraci/tooldoce")
    args = ap.parse_args()

    raiz = gd.Leiaute().raiz()
    todas = list(gd.estruturas(raiz))
    nomes = nomes_unicos(todas)
    compartilhados = tipos_compartilhados(todas)
    pais = {}
    for e in todas:
        for filho in gd.filhos(e.conteudo):
            if filho.estrutura and filho.caminho not in pais:
                pais[filho.caminho] = e
    grupos = {}
    for e in todas:  # ordem do leiaute: pais antes dos filhos
        grupos.setdefault(chave_grupo(e, compartilhados), []).append(e)
    feitos = gd.marcados_todo()

    os.makedirs(args.saida, exist_ok=True)
    with open(os.path.join(args.saida, "indice.tsv"), "w",
              encoding="utf-8") as idx:
        for n, (chave, locais) in enumerate(grupos.items(), 1):
            e = locais[0]
            if len(locais) == 1:
                titulo = f"[Estrutura] {e.caminho.replace('/', ' › ')}"
            else:
                nomes_loc = sorted({x.nome for x in locais})
                titulo = (f"[Estrutura] {'/'.join(nomes_loc)} "
                          f"(tipo {e.tipo})")
            pai = pais.get(e.caminho)
            chave_pai = chave_grupo(pai, compartilhados) if pai else ""
            feito = all(x.caminho in feitos for x in locais)
            corpo = corpo_issue(locais, nomes, args.repo, pais)
            arq = os.path.join(args.saida, f"{n:03d}.md")
            with open(arq, "w", encoding="utf-8") as f:
                f.write(f"título: {titulo}\n{corpo}")
            idx.write(f"{n:03d}\t{chave}\t{chave_pai}\t"
                      f"{'feito' if feito else ''}\t{titulo}\n")
    print(f"{len(grupos)} issues ({len(todas)} estruturas) em {args.saida}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
