#!/usr/bin/env python3
"""Gera o texto das issues de implementação de cada estrutura da NF-e.

Usa o mesmo modelo de tools/gerar_diagramas.py (lido do XSD oficial) e
escreve um arquivo Markdown por estrutura em um diretório de saída, com:
título, diagrama, tabela de campos (obrigatoriedade, ocorrências, tipo,
tamanho, valores e padrão), funções a implementar (criação/liberação,
setters com as validações do leiaute, inclusão de filhos, escrita do XML)
e critérios de aceite.

Uso (na raiz do projeto):
    python3 tools/gerar_issues.py SAIDA [--repo dono/repositorio]

Cada arquivo começa com uma linha "título: ..." seguida do corpo da issue.
Também é gerado SAIDA/indice.tsv com: caminho, caminho do pai, título.
"""
import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import gerar_diagramas as gd  # noqa: E402

RODAPE = "\n---\n_Generated by [Claude Code](https://claude.ai/code)_\n"


def nomes_unicos(estruturas):
    """Nome curto de cada estrutura para as funções (nfe_<nome>_...).

    Usa o nome do elemento; se ele se repetir em outro caminho, junta o
    nome do pai (ex.: impostoDevol/IPI -> impostodevol_ipi)."""
    contagem = {}
    for e in estruturas:
        contagem[e.nome] = contagem.get(e.nome, 0) + 1
    nomes = {}
    for e in estruturas:
        partes = e.caminho.split("/")
        nome = e.nome if contagem[e.nome] == 1 else "_".join(partes[-2:])
        nomes[e.caminho] = nome.lower()
    return nomes


def descreve_validacao(f, tipo):
    """Texto da validação de um campo simples, a partir das facetas."""
    v = []
    if "enumeration" in f:
        v.append("valores: " + ", ".join(f"`{x}`" for x in f["enumeration"]))
    if "length" in f:
        v.append(f"tamanho exato {f['length']}")
    elif "minLength" in f or "maxLength" in f:
        v.append(f"tamanho {f.get('minLength', '0')} a "
                 f"{f.get('maxLength', '?')} caracteres")
    if "pattern" in f:
        v.append(f"padrão `{f['pattern']}`")
    if not v and tipo:
        v.append(f"tipo `{tipo}`")
    return "; ".join(v)


def tipo_c(f, tipo):
    """Tipo C sugerido para o setter de um campo simples."""
    t = (tipo or "").lower()
    if t.startswith("tdec"):
        return "const char *"  # decimal com casas fixas: texto validado
    return "const char *"


def itens_com_contexto(grupo, escolha=None):
    """(item, rótulo da escolha) de cada elemento, atravessando grupos."""
    for item in grupo.itens:
        if isinstance(item, gd.Grupo):
            rotulo = escolha
            if item.tipo == "choice":
                rotulo = "escolha"
            yield from itens_com_contexto(item, rotulo)
        else:
            yield item, escolha


def escape_tabela(t):
    return t.replace("|", "\\|")


def corpo_issue(e, nomes, repo, pai):
    nome = nomes[e.caminho]
    url_svg = (f"https://github.com/{repo}/blob/master/docs/diagramas/"
               f"{e.caminho}.svg")
    oc = gd.ocorrencia(e.minimo, e.maximo) or "1"
    linhas = []
    linhas.append(f"## Estrutura `{e.caminho.replace('/', ' › ')}`")
    linhas.append("")
    if e.doc:
        linhas.append(f"{e.doc}")
        linhas.append("")
    linhas.append(f"- Ocorrência no pai: `{oc}`"
                  + (" (opcional)" if e.minimo == "0" else ""))
    if pai:
        linhas.append(f"- Estrutura pai: `{pai.caminho.replace('/', ' › ')}`")
    linhas.append(f"- Diagrama: [{e.caminho}.svg]({url_svg})")
    linhas.append("")
    linhas.append(f"![Diagrama de {e.nome}]({url_svg}?raw=true)")
    linhas.append("")

    # campos
    linhas.append("## Campos")
    linhas.append("")
    linhas.append("| Campo | Obrig. | Ocorr. | Tipo | Validação | Descrição |")
    linhas.append("|---|---|---|---|---|---|")
    for at in e.atributos:
        linhas.append(
            f"| `{at.nome}` | {'sim' if at.minimo == '1' else 'não'} | | "
            f"{escape_tabela(at.tipo)} | "
            f"{escape_tabela(descreve_validacao(at.facetas, at.tipo))} | "
            f"{escape_tabela(at.doc)} |")
    escolhas = False
    for item, ctx in itens_com_contexto(e.conteudo):
        escolhas = escolhas or ctx == "escolha"
        obrig = "não" if item.minimo == "0" else (
            "escolha" if ctx == "escolha" else "sim")
        ocorr = gd.ocorrencia(item.minimo, item.maximo) or "1"
        if item.estrutura:
            tipo = "estrutura"
            val = f"ver issue/diagrama de `{item.nome}`"
        else:
            tipo = item.tipo
            val = descreve_validacao(item.facetas, item.tipo)
        linhas.append(f"| `{item.nome}` | {obrig} | {ocorr} | "
                      f"{escape_tabela(tipo)} | {escape_tabela(val)} | "
                      f"{escape_tabela(item.doc)} |")
    linhas.append("")
    if escolhas:
        linhas.append("> Campos marcados como **escolha** pertencem a um "
                      "`xs:choice`: apenas um ramo pode ser informado "
                      "(ver o diagrama).")
        linhas.append("")

    # funções
    linhas.append("## Funções a implementar")
    linhas.append("")
    linhas.append("Seguindo `docs/CONVENCOES.md` (tipo opaco, retorno `int` "
                  "com códigos de `erros.h`, sem impressão):")
    linhas.append("")
    linhas.append(f"- [ ] `nfe_{nome} *nfe_{nome}_new(void)` — cria com "
                  "valores padrão; `NULL` se faltar memória")
    linhas.append(f"- [ ] `void nfe_{nome}_free(nfe_{nome} *obj)` — libera "
                  "o objeto e os filhos que ele possui; aceita `NULL`")
    for at in e.atributos:
        val = descreve_validacao(at.facetas, at.tipo)
        linhas.append(f"- [ ] `int nfe_{nome}_set_{at.nome[1:].lower()}"
                      f"(nfe_{nome} *obj, const char *valor)` — atributo; "
                      f"{val}")
    for item, ctx in itens_com_contexto(e.conteudo):
        campo = item.nome.lower()
        if item.estrutura:
            filho = nomes.get(item.caminho, campo)
            if item.maximo not in ("1", "0"):
                lim = "sem limite" if item.maximo == "unbounded" \
                    else f"até {item.maximo}"
                linhas.append(
                    f"- [ ] `int nfe_{nome}_add_{campo}(nfe_{nome} *obj, "
                    f"nfe_{filho} *{campo})` — inclui um `{item.nome}` "
                    f"({lim}); o objeto passa a ser dono do filho")
            else:
                linhas.append(
                    f"- [ ] `int nfe_{nome}_set_{campo}(nfe_{nome} *obj, "
                    f"nfe_{filho} *{campo})` — define o `{item.nome}`; o "
                    f"objeto passa a ser dono do filho")
        else:
            val = descreve_validacao(item.facetas, item.tipo)
            if item.maximo not in ("1", "0"):
                linhas.append(
                    f"- [ ] `int nfe_{nome}_add_{campo}(nfe_{nome} *obj, "
                    f"{tipo_c(item.facetas, item.tipo)}valor)` — campo "
                    f"repetível ({gd.ocorrencia(item.minimo, item.maximo)}); "
                    f"{val}")
            else:
                linhas.append(
                    f"- [ ] `int nfe_{nome}_set_{campo}(nfe_{nome} *obj, "
                    f"{tipo_c(item.facetas, item.tipo)}valor)` — {val}")
    linhas.append(f"- [ ] `int nfe_{nome}_write_xml(xmlTextWriterPtr writer, "
                  f"const nfe_{nome} *obj)` — escreve `<{e.nome}>` na ordem "
                  "do leiaute; recusa (`E_VALOR`) se faltar campo "
                  "obrigatório ou se mais de um ramo de uma escolha estiver "
                  "preenchido")
    linhas.append("")
    linhas.append("Validações dos setters: as da coluna *Validação* acima "
                  "(tamanho em caracteres UTF-8, valores permitidos e padrão "
                  "do XSD). Valores decimais (`TDec_*`) são recebidos como "
                  "texto e validados contra o padrão; CNPJ/CPF usam "
                  "`nfe_cnpj_validar`/`nfe_cpf_validar`.")
    linhas.append("")

    # aceite
    linhas.append("## Critérios de aceite")
    linhas.append("")
    linhas.append("- [ ] Header em `include/libnfe/` e implementação em "
                  "`src/libnfe/`, formatados (`make formatar`)")
    linhas.append("- [ ] Testes em `tests/` cobrindo cada setter (valores "
                  "válidos e inválidos) e a escrita do XML")
    linhas.append("- [ ] XML gerado validado contra o XSD oficial nos testes")
    linhas.append("- [ ] Item marcado no `TODO.md`")
    linhas.append("")
    linhas.append("_Gerado a partir de `leiauteNFe_v4.00.xsd` por "
                  "`tools/gerar_issues.py`._")
    return "\n".join(linhas) + "\n" + RODAPE


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("saida")
    ap.add_argument("--repo", default="icaroraci/tooldoce")
    args = ap.parse_args()

    raiz = gd.Leiaute().raiz()
    todas = list(gd.estruturas(raiz))
    nomes = nomes_unicos(todas)
    pais = {}
    for e in todas:
        for filho in gd.filhos(e.conteudo):
            if filho.estrutura and filho.caminho not in pais:
                pais[filho.caminho] = e

    os.makedirs(args.saida, exist_ok=True)
    with open(os.path.join(args.saida, "indice.tsv"), "w",
              encoding="utf-8") as idx:
        for e in todas:
            titulo = f"[Estrutura] {e.caminho.replace('/', ' › ')}"
            pai = pais.get(e.caminho)
            corpo = corpo_issue(e, nomes, args.repo, pai)
            arq = os.path.join(args.saida, e.caminho.replace("/", "__")
                               + ".md")
            with open(arq, "w", encoding="utf-8") as f:
                f.write(f"título: {titulo}\n{corpo}")
            idx.write(f"{e.caminho}\t{pai.caminho if pai else ''}\t"
                      f"{titulo}\n")
    print(f"{len(todas)} issues em {args.saida}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
